# see rules https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml
# and explanations https://detekt.dev/docs/rules/comments

build:
  maxIssues: 0
  excludeCorrectable: false

comments:
  active: true

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 10
  ComplexInterface:
    active: true
    threshold: 10
    includeStaticDeclarations: false
    includePrivateDeclarations: false
    ignoreOverloaded: false
  CognitiveComplexMethod:
    active: true
    threshold: 15
  CyclomaticComplexMethod:
    active: true
    threshold: 15
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
    ignoreNestingFunctions: false
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
    ignoreDefaultParameters: false
    ignoreDataClasses: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false

coroutines:
  active: true

exceptions:
  active: true

formatting: # seems deprecated and mostly moved to the 'style' section
  active: false

naming:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 180
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  ReturnCount:
    active: false
