spring:
  application.name: "software-updates-bot"
  main.banner-mode: log
  pid:
    fail-on-write-error: false
    file: sub.pid
logging:
  level.root: INFO
  file.path: "logs/"

localapp:
  reportfile:
    json: "report/report.json"
    md: "report/report.md"
    md-by-date: "report/report-by-date.md"
    rss: "report/report.rss.xml"
    atom: "report/report.atom.xml"
    props: "report/report.properties"
    uc: "report/uc.properties"
    jb-marketplace-plugins-latest-all: "report/report.jb-marketplace-plugins-all.rss.xml"
    jb-marketplace-plugins-latest-jetbrains: "report/report.jb-marketplace-plugins-jetbrains.rss.xml"
  statusfile:
    md: "report/status.md"
    rss: "report/status.rss.xml"
    atom: "report/status.atom.xml"
