spring:
  application.name: "software-updates-bot"
  main.banner-mode: off
logging:
  level.root: INFO
  file.path: "logs/"

localapp:
  reportfile:
    json: "report/report.json"
    md: "report/report.md"
    md-by-date: "report/report-by-date.md"
    rss: "report/report.rss.xml"
    atom: "report/report.atom.xml"
  statusfile:
    md: "report/status.md"
    rss: "report/status.rss.xml"
    atom: "report/status.atom.xml"
