# see https://github.com/marketplace/actions/gradle-wrapper-validation
name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "Validation"
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
