name: Run bot
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
        with:
          ref: master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build app
        run: ./gradlew clean bootJar
      - name: Run app
        run: java -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8 -jar build/libs/software-updates-bot-0.0.1-SNAPSHOT.jar
      - name: Prepare files to commit
        run: git update-index --refresh
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "autocommit by bot [ci skip]"
          commit_user_name: Jonathan Lermitage software-updates-bot
          commit_user_email: "software-update-bot@lermitage.biz"
          commit_author: Jonathan Lermitage software-updates-bot <software-update-bot@lermitage.biz>
          file_pattern: 'report/*.md report/*.json report/*.xml'
          skip_dirty_check: false
